### ISSUE TITLE
Update sample agent config file

### ISSUE THREAD

**Issue by nickhammond** [telemetryapp/gotelemetry_agent#2]
https://github.com/telemetryapp/gotelemetry_agent/blob/master/sample_config.yaml

Running the agent with the same configuration file that was working fine with `1.1.RC2`, just changed `api_key` to `api_token`.
```
../agent/telemetry_agent --verbosity=debug --config="./agent-config.yml"
```

agent-config.yml
```
accounts:
  - api_token: abc234
    submission_interval: 1
    jobs:
      - id: reg_and_events-types
        plugin: com.telemetryapp.process
        config:
          path: agents/registration
          flow_tag: reg_and_events-types
          variant: piechart
          refresh: 600
```

```
Telemetry Agent v 1.2
Copyright © 2012-2015 Telemetry, Inc.

For license information, see the LICENSE file
---------------------------------------------

2015/03/05 13:01:01 Initialization error: No API Token found in the configuration file or in the TELEMETRY_API_TOKEN environment variable.
```

**Comment by mtabini** [comment]
Good catch; we'll update the file. Thanks!

You should be able to make your file work by making this changes:

```yaml
api_token: abc234
submission_interval: 1
jobs:
  - config:
      path: agents/registration
      flow_tag: reg_and_events-types
      refresh: 600
```

Couple notes:

- The `id` property is now optional; if you do not include it, it will be set to the value of `flow_tag`
- The `variant` property is now optional unless you specify a `template` (so you could remove it from here)
- The `submission_interval` defaults to 1, so you should also be able to remove that.

LMK if that works!
